repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      -   id: check-yaml
      -   id: check-toml
      -   id: check-shebang-scripts-are-executable
      # -   id: end-of-file-fixer
      # -   id: trailing-whitespace
  - repo: local
    hooks:
      - id: quality-checks
        name: Quality Checks (Ruff, MyPy, Tests, etc.)
        entry: src/tools/run_quality_checks.sh
        language: system
        pass_filenames: false
        always_run: true
